# Start with NVIDIA's development container
FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

# Install system dependencies for Python and JupyterLab
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv python-is-python3 build-essential libopenblas-dev libatlas-base-dev gcc g++ curl wget \
    && rm -rf /var/lib/apt/lists/*

# Add arguments for host UID and GID
ARG HOST_UID
ARG HOST_GID

# Create a non-root user 'suber' with the host UID and GID
RUN groupadd -g ${HOST_GID} suber && \
    useradd -u ${HOST_UID} -g ${HOST_GID} -ms /bin/bash suber

# Set the working directory to /app and change ownership to 'suber' user
WORKDIR /app
RUN chown -R suber:suber /app

# Switch to the non-root user 'suber'
USER suber

# Set environment variables for building lightfm
ENV CFLAGS="-fcommon"
ENV PYTHONOPTIMIZE=1

# Create and activate the virtual environment named 'sb3'
RUN python3 -m venv /app/sb3

# Set the environment variable to activate the virtual environment by default
ENV PATH="/app/sb3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV TORCH_CUDA_ARCH_LIST='6.0;6.1;7.0;7.2;7.5;8.0;8.6+PTX;8.9;9.0'
ENV TF_CPP_MIN_LOG_LEVEL=3

# Upgrade pip and install dependencies, create kernel, and set default kernel
RUN pip install --upgrade pip setuptools wheel ipykernel ipywidgets jupyterlab tqdm swifter swifter[jupyter] swifter[groupby] pydantic-ai \
    && pip install 'pydantic-ai-slim[openai]' modin[all] \
    && pip install tensorflow[and-cuda]==2.15.1 \
    && pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu118

RUN pip install sentence_transformers exllama datasets stable-baselines3 stable-baselines3[extra]
RUN pip install recommenders
RUN pip install SPARQLWrapper
RUN python -m ipykernel install --user --name sb3 --display-name "Python (sb3)" \
    && mkdir -p /home/suber/.jupyter \
    && echo "c.ServerApp.default_kernel_name = 'sb3'" >> /home/suber/.jupyter/jupyter_notebook_config.py

# Expose the JupyterLab port
EXPOSE 8889

# Start JupyterLab upon container startup
CMD ["jupyter-lab", "--ip=0.0.0.0", "--port=8889", "--no-browser", "--allow-root", "--notebook-dir=/app/SUBERX/jupyter/", "--NotebookApp.token=''"]
