# Docker file for Pydantic AI
FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04
#FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
# Install system dependencies for Python and JupyterLab
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv python-is-python3 build-essential libopenblas-dev libatlas-base-dev gcc g++ \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user 'suber'
RUN useradd -ms /bin/bash pyai

# Set the working directory to /app and change ownership to 'suber' user
WORKDIR /app
RUN chown -R pyai:pyai /app

# Switch to the non-root user 'suber'
USER pyai

# Set environment variables for building lightfm
ENV CFLAGS="-fcommon"
ENV PYTHONOPTIMIZE=1

# Create and activate the virtual environment named 'sb3'
RUN python3 -m venv /app/pyai

# Set the environment variable to activate the virtual environment by default
#ENV PATH="/usr/local/cuda/bin:/app/sb3/bin:$PATH"
ENV PATH="/app/pyai/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV TORCH_CUDA_ARCH_LIST='6.0;6.1;7.0;7.2;7.5;8.0;8.6+PTX;8.9;9.0'
ENV TF_CPP_MIN_LOG_LEVEL=3

# Upgrade pip and install dependencies, create kernel, and set default kernel
RUN pip install --upgrade pip setuptools wheel ipykernel ipywidgets jupyterlab tqdm pydantic-ai \
    && pip install 'pydantic-ai-slim[openai]'
#RUN pip install tensorflow[and-cuda]==2.15.1
#RUN pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu118
#RUN pip install sentence_transformers exllama datasets stable-baselines3 stable-baselines3[extra] recommenders
RUN python -m ipykernel install --user --name pyai --display-name "Python (pyai)" \
    && mkdir -p /home/pyai/.jupyter \
    && echo "c.ServerApp.default_kernel_name = 'pyai'" >> /home/pyai/.jupyter/jupyter_notebook_config.py

# Expose the JupyterLab port
EXPOSE 8890

# Start JupyterLab upon container startup
#CMD ["jupyter-lab", "--ip=0.0.0.0", "--port=8890", "--no-browser", "--allow-root", "--notebook-dir=/app", "--NotebookApp.token=''"]
CMD ["/bin/bash", "-c", "source /app/pyai/bin/activate && jupyter-lab --ip=0.0.0.0 --port=8890 --no-browser --allow-root --notebook-dir=/app --NotebookApp.token=''"]
