version: '3.8'

networks:
  cicero:
    driver: bridge

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - cicero
    ports:
      - "11434:11434"
    volumes:
      - /home/asheller/ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.owui
    container_name: open-webui-container
    networks:
      - cicero
    ports:
      - "8080:8080"
    volumes:
      - ./openwebui-data:/app/backendq  # Persist open-webui data
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  fabric:
    build:
      context: .
      dockerfile: Dockerfile.fabric
    container_name: fabric-container
    networks:
      - cicero
    volumes:
      - ./fabric-config:/home/fab_user/.config/fabric
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
